name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        working-directory: ./Ohjelmistotuotanto-2021/viikko3/web-login-robot/
        run: poetry install
      - name: Run robot tests
        run: bash run_robot_tests.sh
